version: "3"

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    volumes:
      - ./postgres/init:/docker-entrypoint-initdb.d
    hostname: postgres
    restart: always
    user: root

  adminer:
    image: adminer
    restart: always
    ports:
    - 8080:8080
